---
- name: "Delete Cluster"
  vars_prompt:

    - name: CLUSTER_NAME
      prompt: "Please enter cluster name:"
      private: no

    - name: S3_BUCKET
      prompt: "Please enter S3 bucket name:"
      private: no

  hosts: localhost

  environment:
    AWS_ACCESS_KEY: "{{ my_access_key }}"
    AWS_SECRET_KEY: "{{ my_secret_key }}"

  gather_facts: no
  roles:
  - delete-rds   
  - delete-cluster
