---
- name: "Launch Network Infrastructure"
  hosts: localhost
  gather_facts: yes
  vars_prompt:

    - name: my_ip
      prompt: "Please enter your machine ip:"
      private: no

  roles:
  - launch-jenkins-create-infrastructure
  environment:
    aws_profile: "{{ aws_profile }}"

- name: "Launch Jenkins"
  hosts: localhost
  gather_facts: no
  vars_prompt:

    - name: key_pair
      prompt: "Please enter key_pair:"
      private: no
  roles:
  - launch-jenkins-ec2  

- name: "Install Updates on ec2"
  hosts: jenkins_server
  remote_user: ubuntu
  become: yes
  gather_facts: no
  vars_prompt:

    - name: jenkins_dns_name
      prompt: "Please enter jenkins subdomain name:"
      private: no

    - name: email
      prompt: "Please enter your email:"
      private: no

    - name: ansible_ssh_private_key_file
      prompt: "Please enter your private key file:"
      private: no

  roles:
    - install-jenkins-on-ec2


