---
- name: Create EC2 Instance
  ec2_instance:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    image_id: "{{ image_id }}"
    key_name: "{{ key_pair }}"
    security_group: "{{ sg_jenkins_ec2.group_id }}"
    instance_type: "t2.small"
    state: present
    vpc_subnet_id: "{{ subnet1.subnet.id }}"
    wait: yes
    tags:
      app: jenkins
    wait_timeout: 600
  register: ec2

- name: Wait for instance to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    state: started
  with_items: "{{ ec2.instances }}"

- name: Allocate Elastic IP address
  ec2_eip:
    region: "{{ aws_region }}"
    profile: "{{ aws_profile }}"
    instance_id: "{{ ec2.instance_ids[0] }}"
    reuse_existing_ip_allowed: yes
    release_on_disassociation: no
    in_vpc: yes
    state: present
    tag_name: "{{ eip_tag_name }}"
    tag_value: "{{ eip_tag_value }}"
  register: eip_info


- name: Add Jenkins Instance to inventory
  add_host:
    name: "{{ eip_info.public_ip }}"
    groups: "{{ server_group_name }}"